### ISSUE TITLE
Error while creating vault

### ISSUE THREAD

**Issue by geimist** [vh13294/crytomator-docker#3]
I get the following error message on startup:
`Exception in thread "main" java.nio.file.NoSuchFileException: /cryptomatorDir/vault.cryptomator`

Does the vault already have to exist? I would like to have it created if it does not already exist with the specified parameters.
Or is the error somewhere else?

Thank you

<details>
  <summary>Full log with demo data</summary>

```
21:12:26.579 [main] INFO  o.c.frontend.webdav.WebDavServer - Binding server socket to 0.0.0.0:8181
21:12:26.626 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@35fc6dc4{HTTP/1.1, (http/1.1)}{0.0.0.0:8181}
21:12:26.632 [main] INFO  org.eclipse.jetty.server.Server - jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 20+36-2344
21:12:26.717 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7f416310{/,null,AVAILABLE}
21:12:26.744 [main] INFO  org.eclipse.jetty.server.Server - Started Server@1d082e88{STARTING}[10.0.6,sto=0] @901ms
21:12:26.744 [main] INFO  o.c.frontend.webdav.WebDavServer - WebDavServer started.
21:12:26.744 [main] INFO  org.cryptomator.cli.frontend.WebDav - WebDAV server started: 0.0.0.0:8181
21:12:26.770 [main] INFO  org.cryptomator.cli.CryptomatorCli - Unlocking vault "demoVault" located at /cryptomatorDir
21:12:26.771 [main] INFO  o.c.c.p.PasswordFromPropertyStrategy - Vault 'demoVault' password from property.
Exception in thread "main" java.nio.file.NoSuchFileException: /cryptomatorDir/vault.cryptomator
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3263)
        at java.base/java.nio.file.Files.readString(Files.java:3341)
        at org.cryptomator.cryptofs.CryptoFileSystems.readVaultConfigFile(CryptoFileSystems.java:113)
        at org.cryptomator.cryptofs.CryptoFileSystems.create(CryptoFileSystems.java:49)
        at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:194)
        at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:86)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
        at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:126)
        at org.cryptomator.cli.CryptomatorCli.startup(CryptomatorCli.java:101)
        at org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:43)
```
</details>

**Comment by vh13294** [comment]
[https://github.com/cryptomator/cli/issues/31](https://github.com/cryptomator/cli/issues/31)

This is the issue from the main cryptomator cli repo.

**Comment by ArnaudSoda** [comment]
> I get the following error message on startup: `Exception in thread "main" java.nio.file.NoSuchFileException: /cryptomatorDir/vault.cryptomator`
> 
> Does the vault already have to exist? I would like to have it created if it does not already exist with the specified parameters. Or is the error somewhere else?
> 
> Thank you
> Full log with demo data
> 
> ```
> 21:12:26.579 [main] INFO  o.c.frontend.webdav.WebDavServer - Binding server socket to 0.0.0.0:8181
> 21:12:26.626 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@35fc6dc4{HTTP/1.1, (http/1.1)}{0.0.0.0:8181}
> 21:12:26.632 [main] INFO  org.eclipse.jetty.server.Server - jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 20+36-2344
> 21:12:26.717 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7f416310{/,null,AVAILABLE}
> 21:12:26.744 [main] INFO  org.eclipse.jetty.server.Server - Started Server@1d082e88{STARTING}[10.0.6,sto=0] @901ms
> 21:12:26.744 [main] INFO  o.c.frontend.webdav.WebDavServer - WebDavServer started.
> 21:12:26.744 [main] INFO  org.cryptomator.cli.frontend.WebDav - WebDAV server started: 0.0.0.0:8181
> 21:12:26.770 [main] INFO  org.cryptomator.cli.CryptomatorCli - Unlocking vault "demoVault" located at /cryptomatorDir
> 21:12:26.771 [main] INFO  o.c.c.p.PasswordFromPropertyStrategy - Vault 'demoVault' password from property.
> Exception in thread "main" java.nio.file.NoSuchFileException: /cryptomatorDir/vault.cryptomator
>         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
>         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
>         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
>         at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
>         at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
>         at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
>         at java.base/java.nio.file.Files.readAllBytes(Files.java:3263)
>         at java.base/java.nio.file.Files.readString(Files.java:3341)
>         at org.cryptomator.cryptofs.CryptoFileSystems.readVaultConfigFile(CryptoFileSystems.java:113)
>         at org.cryptomator.cryptofs.CryptoFileSystems.create(CryptoFileSystems.java:49)
>         at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:194)
>         at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:86)
>         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
>         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
>         at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:126)
>         at org.cryptomator.cli.CryptomatorCli.startup(CryptomatorCli.java:101)
>         at org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:43)
> ```

I face the same issue. Not able to solve it
